src/Entity/Servicios.php
<?php

namespace App\Entity;

use App\Repository\ServiciosRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ServiciosRepository::class)]
class Servicios
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nombre = null;

    #[ORM\OneToMany(mappedBy: 'servicios', targetEntity: Calendar::class)]
    private Collection $calendars;

    #[ORM\OneToMany(mappedBy: 'servicios', targetEntity: Tutor::class)]
    private Collection $tutor;

    public function __construct()
    {
        $this->citas = new ArrayCollection();
        $this->calendars = new ArrayCollection();
        $this->tutor = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    /**
     * @return Collection<int, Calendar>
     */
    public function getCalendars(): Collection
    {
        return $this->calendars;
    }

    public function addCalendar(Calendar $calendar): self
    {
        if (!$this->calendars->contains($calendar)) {
            $this->calendars->add($calendar);
            $calendar->setServicios($this);
        }

        return $this;
    }

    public function removeCalendar(Calendar $calendar): self
    {
        if ($this->calendars->removeElement($calendar)) {
            // set the owning side to null (unless already changed)
            if ($calendar->getServicios() === $this) {
                $calendar->setServicios(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Tutor>
     */
    public function getTutor(): Collection
    {
        return $this->tutor;
    }

    public function addTutor(Tutor $tutor): self
    {
        if (!$this->tutor->contains($tutor)) {
            $this->tutor->add($tutor);
            $tutor->setServicios($this);
        }

        return $this;
    }

    public function removeTutor(Tutor $tutor): self
    {
        if ($this->tutor->removeElement($tutor)) {
            // set the owning side to null (unless already changed)
            if ($tutor->getServicios() === $this) {
                $tutor->setServicios(null);
            }
        }

        return $this;
    }

}

src/Controller/FamiliaController.php
<?php

namespace App\Controller;

use App\Entity\Reserva;
use App\Repository\CalendarRepository;
use App\Repository\ReservaRepository;
use App\Repository\TutorRepository;
use App\Repository\UserRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class FamiliaController extends AbstractController
{

    private $requestStack;
    

    public function __construct(RequestStack $requestStack)
    {
        $this->requestStack = $requestStack;
    }

    public function menuFamilias(AuthenticationUtils $authenticationUtils,$id)
    {
        $session = $this->requestStack->getSession();
        $servicio = $session->get('servicio');
        $lastUsername = $authenticationUtils->getLastUsername();
        return $this->render('familia/menu.html.twig', ['username' => $lastUsername,'servicio' => $servicio,'id' => $id]);
    }

    #[Route('anular/{id}', name:'anular')]
    public function anular(ManagerRegistry $doctrine, $id)
    {
        $reservaRepository = new ReservaRepository($doctrine, $doctrine->getManager());
        $reserva = $reservaRepository->findOneBy(['id' => $id]);
        $calendar = $reserva->getCalendar();
        $calendar->setDisabled(false);
        $em = $doctrine->getManager();
        $em->remove($reserva);
        $em->flush();
        $session = $this->requestStack->getSession();
        $session->start();
        $servicio = $session->get('servicio');
        return $this->render('familia/anulaReserva.html.twig', ['servicio' => $servicio,'trabajador' => $session->get('trabajador')]);
    }

    //CÓDIGO DE TUTORÍA

    #[Route('/familia/tutor', name: 'showTutores')]
    public function listadoTutoria(Request $request,ManagerRegistry $doctrine): Response
    {
        $tutorRepository = new TutorRepository($doctrine);
        $tutores = $tutorRepository->findBy(['servicios' => 3]);
        $form = $this->createFormBuilder()
                    // ->add('Tutor', EntityType::class, ['label' => 'Seleccione tutor ', 'class' => Tutor::class, 'choice_label' => $tutores])
                    ->add('Elegir', SubmitType::class)
                    ->getForm();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            $session = $this->requestStack->getSession();
            $session->start();
            $session->set('tutor', $_POST['selectTutores']);
            return $this->redirectToRoute('tutoria');
        }
        return $this->render('familia/listarTutores.html.twig', ['form' => $form->createView(),'tutores' => $tutores]);
    }


    #[Route('/familia/tutor/Tutoría', name: 'tutoria')]
    public function indexTutoria(ManagerRegistry $doctrine,AuthenticationUtils $authenticationUtils,CalendarRepository $calendar): Response
    {
        $session = $this->requestStack->getSession();
        $session->start();
        $lastUsername = $authenticationUtils->getLastUsername();
        $calendarRepository = new CalendarRepository($doctrine);
        $calendar = $calendarRepository->findBy(['servicios'=>3,'tutor' => $session->get('tutor'),'disabled' => false]);
        $rdvs = [];
        foreach($calendar as $event){
            $rdvs[] = [
                'id' => $event->getId(),
                'start' => $event->getStart()->format('Y-m-d H:i:s'),
                'end' => $event->getEnd()->format('Y-m-d H:i:s'),
                'title' => $event->getTitle(),
                'description' => $event->getDescription(),
                'backgroundColor' => $event->getBackgroundColor(),
                'borderColor' => $event->getBorderColor(),
                'textColor' => $event->getTextColor(),
            ];
        }
        $data = $this->json($rdvs);

        $session = $this->requestStack->getSession();
        $session->start();
        $session->set('servicio','Tutoría');
        $session->set('trabajador','tutor');

        return $this->render('familia/index.html.twig', ['data' => $data->getContent(),'username' => $lastUsername,'events' => $calendar,'servicio' => 'Tutoría','trabajador' => $session->get('trabajador')]);
    }

    #[Route('/familia/tutor/Tutoría/{id}', name:'tutoria_reserva')]
    public function reservaTutoria(AuthenticationUtils $authenticationUtils,ManagerRegistry $doctrine,$id)
    {
        $session = $this->requestStack->getSession();
        $session->start();
        $idTutor = $session->get('tutor');

        $tutorRepository = new TutorRepository($doctrine);
        $tutor = $tutorRepository->findOneBy(['id' => $idTutor]);
        $username = $authenticationUtils->getLastUsername();
        $calendarRepository = new CalendarRepository($doctrine);
        $event = $calendarRepository->findOneBy(['id' => $id]);
        $userRepository = new UserRepository($doctrine);
        $user = $userRepository->findOneBy(['username' => $username]);
        $reserva = new Reserva();

        $event->setDisabled(true);
        $event->setReserva($reserva);
        $event->setUser($user);
        $reserva->setUsername($username);
        $reserva->setTutor($tutor);
        $reserva->setCalendar($event);
        
        $em = $doctrine->getManager();
        $em->persist($event);
        $em->persist($reserva);
        $em->flush();

        return $this->render('confirmacion/tutoria.html.twig',['event' => $event]);
    }
    
    #[Route('/familia/tutor/Tutoría/consulta/{username}', name:'cita_consulta_tutoria')]
    public function consultasTutoria(string $username,ManagerRegistry $doctrine,AuthenticationUtils $authenticationUtils)
    {
        $username = $authenticationUtils->getLastUsername();
        $reservaRepository = new ReservaRepository($doctrine);
        $reservas = $reservaRepository->findBy(['Username' => $username]);
        $session = $this->requestStack->getSession();
        $session->start();
        $servicio = $session->get('servicio');
        return $this->render('familia/reservas.html.twig', ['reservas' => $reservas,'username' => $username,'servicio' => $servicio,'trabajador' => 'tutor']);
    }

    //CÓDIGO DE ORIENTACIÓN

    #[Route('/familia/orientador', name: 'showOrientacion')]
    public function listadoOrientacion(Request $request,ManagerRegistry $doctrine): Response
    {
        $tutorRepository = new TutorRepository($doctrine);
        $orientadores = $tutorRepository->findBy(['servicios' => 1]);
        $form = $this->createFormBuilder()
                    // ->add('Orientador', EntityType::class, ['label' => 'Seleccione orientador/ora ', 'class' => Tutor::class, 'choice_label' => 'username'])
                    ->add('Elegir', SubmitType::class)
                    ->getForm();
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            $session = $this->requestStack->getSession();
            $session->start();
            var_dump($_POST['selectTutores']);
            $session->set('orientador', $_POST['selectTutores']);
            return $this->redirectToRoute('orientacion');
        }
        return $this->render('familia/listarTutores.html.twig', ['form' => $form->createView(),'tutores' => $orientadores]);
    }

    #[Route('/familia/orientador/Orientación', name: 'orientacion')]
    public function indexOrientacion(ManagerRegistry $doctrine,AuthenticationUtils $authenticationUtils,CalendarRepository $calendar): Response
    {
        $session = $this->requestStack->getSession();
        $session->start();
        $lastUsername = $authenticationUtils->getLastUsername();
        $calendarRepository = new CalendarRepository($doctrine);
        $calendar = $calendarRepository->findBy(['servicios'=>1,'tutor' => $session->get('orientador'),'disabled' => false]);
        $rdvs = [];
        foreach($calendar as $event){
            $rdvs[] = [
                'id' => $event->getId(),
                'start' => $event->getStart()->format('Y-m-d H:i:s'),
                'end' => $event->getEnd()->format('Y-m-d H:i:s'),
                'title' => $event->getTitle(),
                'description' => $event->getDescription(),
                'backgroundColor' => $event->getBackgroundColor(),
                'borderColor' => $event->getBorderColor(),
                'textColor' => $event->getTextColor(),
            ];
        }
        $data = $this->json($rdvs);

        $session = $this->requestStack->getSession();
        $session->start();
        $session->set('servicio','Orientación');
        $session->set('trabajador','orientador');

        return $this->render('familia/index.html.twig', ['data' => $data->getContent(),'username' => $lastUsername,'events' => $calendar,'servicio' => 'Orientación','trabajador' => $session->get('trabajador')]);
    }

    #[Route('/familia/orientador/Orientación/{id}', name:'orientación_reserva')]
    public function reservaOrientación(AuthenticationUtils $authenticationUtils,ManagerRegistry $doctrine,$id)
    {
        $session = $this->requestStack->getSession();
        $session->start();
        $idTutor = $session->get('orientador');

        $tutorRepository = new TutorRepository($doctrine);
        $tutor = $tutorRepository->findOneBy(['id' => $idTutor]);
        $username = $authenticationUtils->getLastUsername();
        $calendarRepository = new CalendarRepository($doctrine);
        $event = $calendarRepository->findOneBy(['id' => $id]);
        $userRepository = new UserRepository($doctrine);
        $user = $userRepository->findOneBy(['username' => $username]);
        $reserva = new Reserva();

templates/familia/anulaReserva.html.twig
{% extends 'base.html.twig' %}
{% block body %}
	<div class="container" id="exito">
	Se ha anulado la reserva
	</div>
	<br>
    {# <a class="btn btn-primary" href="/familia/{{trabajador}}/{{servicio}}">Volver a {{servicio}}</a>  #}
{% endblock %}

templates/familia/exito.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	{% for label, messages in app.flashes %}
		{% for message in messages %}
			<div class="alert alert-{{ label }} alert-dismissible fade show" role="alert">
				{{ message }}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
					<span aria-hidden="true">×</span>
				</button>
			</div>
		{% endfor %}
	{% endfor %}
	<br>
    <a class="btn btn-primary" href="/familia/{{servicio}}">Volver a {{servicio}}</a> 
{% endblock %}

templates/familia/form.html.twig
{% block body %}
	<h1>Citas</h1>

	{{form(form)}}
    <a class="btn btn-primary" href="/familia/{{servicio}}">Volver a {{servicio}}</a> 
	{% endblock %}

templates/familia/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FamiliaController!{% endblock %}

{% block menu %}
    {% set hide_user_nav = true %}
        <nav class="navbar navbar-dark navbar-expand">
            <div class="container-fluid">
                <a href="https://www.iesjoseplanes.es/" target="_blank">
                    <img id="icon" src="/svg/logoPlanesSinFondo.svg">
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                    <div class="navbar-nav ms-auto">
                        {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
                            {% if (hide_user_nav is defined) %}
                                <a class="nav-link" href="/familia/{{trabajador}}/{{servicio}}/consulta/{{username}}">Consulta</a>
                            {% endif %}
                            <a class="nav-link" href="{{ path('app_logout') }}">Cerrar sesión</a>
                        {% else %}
                            <a class="nav-link" href="{{ path('app_login') }}">Iniciar sesión</a>
                            <a class="nav-link" href="{{ path('app_register') }}">Registrar</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
{% endblock %}

{% block body %}

    <div id="calendar">
    </div>


    {# <div class="modal fade" id="myModal" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdrop" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="titulo"></h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form id="formulario">
                    <div class="modal-body">
                        <div class="form-floating mb-3">
                            <input type="date" class="form-control" id="start">
                            <label for="exampleFormControlInput1" class="form-label">Fecha de inicio</label>
                        </div>
                        <div class="mb-3">
                            <label for="exampleFormControlTextarea1" class="form-label">Example textarea</label>
                            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                        </div>
                    </div>
                    <div class="modal-footer">

                    </div>
                </form>    
            </div>
        </div>
    </div> #}
    
    {# {% if citas is empty %}
        No existen citas para mostrar
    {% else %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Fecha</th>
                    <th scope="col">Hora</th>
                    <th scope="col">Servicio</th>
                    <th scope="col">Acciones</th>
                </tr>
            </thead>
            <tbody>
            {% for cita in citas %}
                {% if cita.tutor.id == id %}
                    <tr>
                        <td>{{cita.fecha|date("d/m/Y")}}</td>
                        <td>{{cita.hora|date("H:i:s")}}</td>
                        <td>{{cita.Servicio.nombre}}</td>
                        <td><a href="/familia/{{servicio}}/{{cita.id}}" class="btn btn-primary {% if cita.disabled == true %}disabled{% endif %}">Reservar</a></td>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
        <a href="/familia" class="btn btn-primary">⏪</a>
        {% if is_granted("IS_AUTHENTICATED_REMEMBERED") %}
            <a href="/consulta/{{servicio}}/{{username}}" class="btn btn-primary">Consulta</a>
        {% endif %}
    {% endif %} #}
{% endblock %}

{% block javascripts %}
    <script src="/public/javascripts/moment.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fullcalendar@5.11.3/main.min.js" integrity="sha256-7PzqE1MyWa/IV5vZumk1CVO6OQbaJE4ns7vmxuUP/7g=" crossorigin="anonymous"></script>
    <script src="/public/javascripts/es.js"></script>
    <script>
        window.onload = () => {
            let calendarElt = document.querySelector("#calendar");

            let calendar = new FullCalendar.Calendar(calendarElt, {
                locale: 'es',
                initialView: 'dayGridMonth',
                firstDay: 1,
                timeZone: 'Europe/Madrid',
                /*customButtons: {
                    consulta: {
                        themeIcon: "refresh",
                        text: "Consulta",
                        click: function(){
                            window.open(`/familia/{{trabajador}}/{{servicio}}/consulta/{{username}}`,"_self")
                        }
                    },
                },*/
                headerToolbar: {
                    start: 'prev,next,today',
                    center: 'title',
                    end: 'dayGridMonth,timeGridWeek,listWeek',
                },
                events: {{data|raw}},
                eventClick: function(e) {
                    window.open(`/familia/{{trabajador}}/{{servicio}}/${e.event.id}`,"_self") 
                },
                /*
                monthNamesShort: ['Ene', 'Feb', 'Mar', 'Abr', 'May', 'Jun', 'Jul', 'Ago', 'Sep', 'Oct', 'Nov', 'Dic'],
                monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
                */
                eventResizableFromStart: true,
                dayNames: ['Domingo', 'Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado'],
                dayNamesShort: ['Dom','Lun','Mar','Mie','Jue','Vie','Sáb'],
                buttonText: {
                    today:    'Hoy',
                    month:    'Mes',
                    week:     'Semana',
                    day:      'Día',
                    list:     'Lista'
                },
                allDaySlot: false,
            })
            calendar.render()
        }
    </script>
{% endblock %}

templates/familia/listado.html.twig
{% extends 'base.html.twig' %}
{% block body %}
	<ul>
		{% for cita in citas %}
			<li>{{cita.fecha|date('D-Y-m-d')}}
				a las
				<a href="reserva/{{cita.id}}">{{cita.hora|date('H:i')}}</a>
			</li>
		{% endfor %}

	</ul>
	<br>
    <a class="btn btn-primary" href="/familia/{{servicio}}">Volver a {{servicio}}</a> 
{% endblock %}

templates/familia/listarTutores.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tutores{% endblock %}

{% block body %}

    {# {% for tutor in tutores %}
    <div class="card" style="width: 18rem;">
        <a href="{{path('aniadir_citas')}}">
            <img src="..." class="card-img-top" alt="...">
        </a>
        <div class="card-body">
            <p class="card-text">{{tutor.user.username}}</p>
        </div>
    </div>
    {% endfor %} #}
    <div id="desplegarTutores">
        {# {{ form(form) }} #}
        <div class="container">
        {{ form_start(form) }}
            <label for="tutor">¿Quién quieres que te atienda?</label><br>
            <div class="form-group col-sm-3">
                <select class="form-select" id="selectTutores" name="selectTutores">
                    {% for tutor in tutores %}
                        <option value="{{tutor.id}}">{{tutor.username}}</option>
                    {% endfor %} 
                </select>
            </div><br>
            {{ form_row(form.Elegir) }}
        {{ form_end(form) }}
        </div>
    </div>
    
    
{% endblock %}

templates/familia/menu.html.twig
    <br>
    <a class="btn btn-primary" href="/familia/{{trabajador}}/{{servicio}}">Volver a {{servicio}}</a> 

templates/familia/msg.html.twig
<h1>Información</h1>

{{ msg}}

<br>
<a class="btn btn-primary" href="/familia/{{servicio}}">Volver a {{servicio}}</a> 

templates/familia/reservas.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FamiliaController!{% endblock %}

{% block body %}
	<div id="reservabodyBlock">
		<h1 style="text-align: center;">Reservas</h1>
			{% if reservas is empty %}
				No se han encontrado reservas
			{% else %}
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Le atiende</th>
							<th>Fecha de inicio</th>
							<th>Hora de inicio</th>
							<th>Fecha de fin</th>
							<th>Hora de fin</th>
							<th>Servicio</th>
							<th>Acciones</th>
						</tr>
					</thead>
					<tbody>
						{% for reserva in reservas %}
									{# {{ dump(reserva.calendar.user.username) }} #}
								{% if username == reserva.calendar.user.username and reserva.calendar.servicios.Nombre == servicio %}
									<tr>
										<td>{{ reserva.tutor.username}}</td>
										<td>{{ reserva.calendar.start|date('d-m-Y')}}</td>
										<td>{{ reserva.calendar.start|date('H:i:s')}}</td>
										<td>{{ reserva.calendar.end|date('d-m-Y')}}</td>
										<td>{{ reserva.calendar.end|date('H:i:s')}}</td>
										<td>{{ reserva.calendar.servicios.Nombre}}</td>
										<td><a href="/anular/{{reserva.id}}" class="btn btn-danger">Anular</a></td>
									<tr>
								{% endif %}
						{% endfor %}
					</tbody>
				</table>
				</br>
				<a class="btn btn-primary" href="/familia/{{trabajador}}/{{servicio}}">Volver a {{servicio}}</a>
			{% endif %}
	</div>
{% endblock %}